version: "3.8"
services:
  # MongoDB service with single node replica set
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    entrypoint: ["/usr/bin/mongod","--bind_ip_all","--replSet","rs0"]

  # MongoDB mock server for initializing replica set & generating data
  mongosetup:
    image: mongo
    depends_on:
      - mongodb
    restart: "no"
    volumes:
      - ./mongo-init.js:/mongo-init.js
    entrypoint: [ "bash", "-c", "mongosh 'mongodb://mongodb:27017' --eval 'rs.initiate()' && mongosh 'mongodb://mongodb:27017' mongo-init.js"] 

  # Backend
  api:
    build: ./api
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - NODE_ENV=production
      - NODE_PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - mongosetup
    restart: on-failure

  # Frontend
  webapp:
    build: ./webapp
    ports:
      - 4000:80
    depends_on:
      - api
